/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UserRegistry } from "./UserRegistry";
export * as factories from "./factories";
export { UserRegistry__factory } from "./factories/UserRegistry__factory";
